// Squad data for 2026 World Cup teams.
//
// Honest scope: full final squads aren't named until late May / early June 2026,
// and federations can change managers and captains at short notice. So we hold:
//   - Key figures (manager, captain, top scorer) for the teams where this is
//     reliably known mid-2026.
//   - A list of widely-recognised first-team regulars per team ("notable").
// Photos for each player are not stored — they are looked up at render time via
// the Wikipedia summary API so we don't bundle or re-host imagery. See lib/players.ts.
//
// Any team without an entry falls back to a "Key figures to be confirmed" card —
// which is the right answer when we don't have stable data.

export type KeyFigure = { name: string; wiki?: string; position?: string };
export type SquadInfo = {
  manager?: KeyFigure;
  captain?: KeyFigure;
  topScorer?: KeyFigure;
  // Optional notable subset shown when no full squad has been announced yet.
  notable?: KeyFigure[];
  // Full 26-player squad once announced. When present, the team page renders
  // the full list instead of just the notable subset.
  fullSquad?: KeyFigure[];
  // ISO date when the federation is expected to announce its final squad.
  // Used to message users honestly until the list lands.
  squadAnnouncementDue?: string;
  note?: string;
};

// `wiki` defaults to `name` if omitted. Override when the Wikipedia page title
// differs from the display name (accents, disambiguation suffixes, etc.).
export const SQUADS: Record<string, SquadInfo> = {
  // ── Full squads announced ──────────────────────────────────────────────────

  AUT: {
    manager: { name: "Ralf Rangnick" },
    captain: { name: "David Alaba" },
    fullSquad: [
      { name: "Alexander Schlager" },
      { name: "Florian Wiegele" },
      { name: "Patrick Pentz" },
      { name: "David Affengruber" },
      { name: "Kevin Danso" },
      { name: "Stefan Posch" },
      { name: "David Alaba" },
      { name: "Philipp Lienhart" },
      { name: "Phillipp Mwene" },
      { name: "Alexander Prass" },
      { name: "Marco Friedl" },
      { name: "Michael Svoboda" },
      { name: "Xaver Schlager" },
      { name: "Nicolas Seiwald" },
      { name: "Marcel Sabitzer" },
      { name: "Florian Grillitsch" },
      { name: "Carney Chukwuemeka" },
      { name: "Romano Schmid" },
      { name: "Christoph Baumgartner" },
      { name: "Konrad Laimer" },
      { name: "Patrick Wimmer" },
      { name: "Paul Wanner" },
      { name: "Alessandro Schopf" },
      { name: "Marko Arnautovic" },
      { name: "Michael Gregoritsch" },
      { name: "Sasa Kalajdzic" },
    ],
  },

  BEL: {
    manager: { name: "Rudi Garcia" },
    captain: { name: "Kevin De Bruyne" },
    topScorer: { name: "Romelu Lukaku" },
    fullSquad: [
      { name: "Thibaut Courtois" },
      { name: "Senne Lammens" },
      { name: "Mike Penders" },
      { name: "Timothy Castagne" },
      { name: "Zeno Debast" },
      { name: "Maxim De Cuyper" },
      { name: "Koni De Winter" },
      { name: "Brandon Mechele" },
      { name: "Thomas Meunier" },
      { name: "Nathan Ngoy" },
      { name: "Joaquin Seys" },
      { name: "Arthur Theate" },
      { name: "Kevin De Bruyne" },
      { name: "Amadou Onana" },
      { name: "Nicolas Raskin" },
      { name: "Youri Tielemans" },
      { name: "Hans Vanaken" },
      { name: "Axel Witsel" },
      { name: "Charles De Ketelaere" },
      { name: "Jérémy Doku", wiki: "Jérémy_Doku" },
      { name: "Matias Fernandez-Pardo" },
      { name: "Romelu Lukaku" },
      { name: "Dodi Lukebakio" },
      { name: "Diego Moreira" },
      { name: "Alexis Saelemaekers" },
      { name: "Leandro Trossard" },
    ],
  },

  BIH: {
    manager: { name: "Sergej Barbarez" },
    captain: { name: "Edin Džeko", wiki: "Edin_Džeko" },
    topScorer: { name: "Edin Džeko", wiki: "Edin_Džeko" },
    fullSquad: [
      { name: "Nikola Vasilj" },
      { name: "Martin Zlomislic" },
      { name: "Osman Hadzikic" },
      { name: "Sead Kolašinac", wiki: "Sead_Kolašinac" },
      { name: "Amar Dedić", wiki: "Amar_Dedić" },
      { name: "Nihad Mujakic" },
      { name: "Nikola Katić", wiki: "Nikola_Katić_(footballer)" },
      { name: "Tarik Muharemović" },
      { name: "Stjepan Radeljić" },
      { name: "Dennis Hadzikadunic" },
      { name: "Nidal Čelić" },
      { name: "Amir Hadžiahmetović" },
      { name: "Ivan Šunjić", wiki: "Ivan_Šunjić" },
      { name: "Ivan Basic" },
      { name: "Dženis Burnić", wiki: "Dženis_Burnić" },
      { name: "Ermin Mahmić" },
      { name: "Benjamin Tahirović", wiki: "Benjamin_Tahirović" },
      { name: "Amar Memić" },
      { name: "Armin Gigović" },
      { name: "Kerim Alajbegović" },
      { name: "Esmir Bajraktarević" },
      { name: "Ermedin Demirović", wiki: "Ermedin_Demirović" },
      { name: "Jovo Lukić" },
      { name: "Samed Baždar" },
      { name: "Haris Tabakovic" },
      { name: "Edin Džeko", wiki: "Edin_Džeko" },
    ],
  },

  BRA: {
    manager: { name: "Carlo Ancelotti" },
    captain: { name: "Marquinhos" },
    topScorer: { name: "Neymar" },
    fullSquad: [
      { name: "Alisson", wiki: "Alisson_Becker" },
      { name: "Ederson", wiki: "Ederson_(footballer,_born_1993)" },
      { name: "Weverton" },
      { name: "Marquinhos" },
      { name: "Gabriel", wiki: "Gabriel_Magalhães" },
      { name: "Bremer", wiki: "Gleison_Bremer" },
      { name: "Ibañez", wiki: "Roger_Ibañez" },
      { name: "Leo Pereira" },
      { name: "Wesley" },
      { name: "Danilo", wiki: "Danilo_(footballer,_born_1991)" },
      { name: "Alex Sandro" },
      { name: "Douglas Santos" },
      { name: "Casemiro" },
      { name: "Bruno Guimarães", wiki: "Bruno_Guimarães" },
      { name: "Fabinho", wiki: "Fabinho_(footballer,_born_1993)" },
      { name: "Lucas Paquetá", wiki: "Lucas_Paquetá" },
      { name: "Vinícius Júnior", wiki: "Vinícius_Júnior" },
      { name: "Raphinha" },
      { name: "Matheus Cunha" },
      { name: "Luiz Henrique" },
      { name: "Igor Thiago" },
      { name: "Endrick", wiki: "Endrick_(footballer)" },
      { name: "Gabriel Martinelli", wiki: "Gabriel_Martinelli" },
      { name: "Rayan" },
      { name: "Neymar" },
    ],
  },

  CIV: {
    manager: { name: "Emerse Faé", wiki: "Emerse_Faé" },
    captain: { name: "Seko Fofana" },
    fullSquad: [
      { name: "Yahia Fofana" },
      { name: "Mohamed Koné" },
      { name: "Alban Lafont" },
      { name: "Emmanuel Agbadou" },
      { name: "Clément Akpa" },
      { name: "Ousmane Diomande" },
      { name: "Guela Doué" },
      { name: "Ghislain Konan" },
      { name: "Odilon Kossounou" },
      { name: "Evan Ndicka" },
      { name: "Wilfried Singo" },
      { name: "Seko Fofana" },
      { name: "Parfait Guiagon" },
      { name: "Christ Inao Oulaï" },
      { name: "Franck Kessié", wiki: "Franck_Kessié" },
      { name: "Ibrahim Sangaré", wiki: "Ibrahim_Sangaré" },
      { name: "Jean-Michaël Seri", wiki: "Jean-Michaël_Seri" },
      { name: "Simon Adingra" },
      { name: "Ange-Yoan Bonny" },
      { name: "Amad Diallo" },
      { name: "Oumar Diakité" },
      { name: "Yan Diomande" },
      { name: "Evann Guessand" },
      { name: "Nicolas Pépé", wiki: "Nicolas_Pépé" },
      { name: "Bazoumana Touré" },
      { name: "Elye Wahi" },
    ],
  },

  COD: {
    manager: { name: "Sébastien Desabre", wiki: "Sébastien_Desabre" },
    captain: { name: "Chancel Mbemba" },
    fullSquad: [
      { name: "Matthieu Epolo" },
      { name: "Timothy Fayulu" },
      { name: "Lionel Mpasi" },
      { name: "Dylan Batubinsika" },
      { name: "Rocky Bushiri" },
      { name: "Gedeon Kalulu" },
      { name: "Steve Kapuadi" },
      { name: "Joris Kayembe" },
      { name: "Arthur Masuaku" },
      { name: "Chancel Mbemba" },
      { name: "Axel Tuanzebe" },
      { name: "Aaron Wan-Bissaka" },
      { name: "Theo Bongonda" },
      { name: "Brian Cipenga" },
      { name: "Meshack Elia" },
      { name: "Gaël Kakuta", wiki: "Gaël_Kakuta" },
      { name: "Edo Kayembe" },
      { name: "Nathanael Mbuku" },
      { name: "Samuel Moutoussamy" },
      { name: "Ngal'ayel Mukau" },
      { name: "Charles Pickel" },
      { name: "Noah Sadiki" },
      { name: "Cédric Bakambu", wiki: "Cédric_Bakambu" },
      { name: "Simon Banza" },
      { name: "Fiston Mayele" },
      { name: "Yoane Wissa" },
    ],
  },

  CRO: {
    manager: { name: "Zlatko Dalić" },
    captain: { name: "Luka Modrić", wiki: "Luka_Modrić" },
    topScorer: { name: "Luka Modrić", wiki: "Luka_Modrić" },
    fullSquad: [
      { name: "Dominik Livaković", wiki: "Dominik_Livaković" },
      { name: "Dominik Kotarski" },
      { name: "Ivor Pandur" },
      { name: "Joško Gvardiol", wiki: "Joško_Gvardiol" },
      { name: "Duje Ćaleta-Car", wiki: "Duje_Ćaleta-Car" },
      { name: "Josip Šutalo", wiki: "Josip_Šutalo" },
      { name: "Josip Stanišić", wiki: "Josip_Stanišić" },
      { name: "Marin Pongračić", wiki: "Marin_Pongračić" },
      { name: "Martin Erlić", wiki: "Martin_Erlić" },
      { name: "Luka Vušković" },
      { name: "Luka Modrić", wiki: "Luka_Modrić" },
      { name: "Mateo Kovačić", wiki: "Mateo_Kovačić" },
      { name: "Mario Pašalić", wiki: "Mario_Pašalić" },
      { name: "Nikola Vlašić", wiki: "Nikola_Vlašić" },
      { name: "Luka Sučić", wiki: "Luka_Sučić" },
      { name: "Martin Baturina" },
      { name: "Kristijan Jakić", wiki: "Kristijan_Jakić" },
      { name: "Petar Sučić" },
      { name: "Nikola Moro" },
      { name: "Toni Fruk" },
      { name: "Ivan Perišić", wiki: "Ivan_Perišić" },
      { name: "Andrej Kramarić", wiki: "Andrej_Kramarić" },
      { name: "Ante Budimir" },
      { name: "Marco Pašalić" },
      { name: "Petar Musa" },
      { name: "Igor Matanović" },
    ],
  },

  CUR: {
    manager: { name: "Dick Advocaat" },
    fullSquad: [
      { name: "Tyrick Bodak" },
      { name: "Trevor Doornbusch" },
      { name: "Eloy Room" },
      { name: "Riechedly Bazoer" },
      { name: "Joshua Brenet" },
      { name: "Roshon Van Eijma" },
      { name: "Sherel Floranus" },
      { name: "Deveron Fonville" },
      { name: "Jurien Gaari" },
      { name: "Armando Obispo" },
      { name: "Shurandy Sambo" },
      { name: "Juninho Bacuna" },
      { name: "Leandro Bacuna" },
      { name: "Livano Comenencia" },
      { name: "Kevin Felida" },
      { name: "Ar'Jany Martha" },
      { name: "Tyrese Noslin" },
      { name: "Godfried Roemeratoe" },
      { name: "Jeremy Antonisse" },
      { name: "Tahith Chong" },
      { name: "Kenji Gorré" },
      { name: "Sontje Hansen" },
      { name: "Gervane Kastaneer" },
      { name: "Brandley Kuwas" },
      { name: "Jürgen Locadia" },
      { name: "Jearl Margaritha" },
    ],
  },

  FRA: {
    manager: { name: "Didier Deschamps" },
    captain: { name: "Kylian Mbappé", wiki: "Kylian_Mbappé" },
    topScorer: { name: "Kylian Mbappé", wiki: "Kylian_Mbappé" },
    fullSquad: [
      { name: "Mike Maignan" },
      { name: "Robin Risser" },
      { name: "Brice Samba" },
      { name: "Lucas Digne" },
      { name: "Malo Gusto" },
      { name: "Lucas Hernández", wiki: "Lucas_Hernández_(footballer,_born_1996)" },
      { name: "Theo Hernández", wiki: "Theo_Hernández" },
      { name: "Ibrahima Konaté", wiki: "Ibrahima_Konaté" },
      { name: "Jules Koundé", wiki: "Jules_Koundé" },
      { name: "Maxence Lacroix" },
      { name: "William Saliba" },
      { name: "Dayot Upamecano" },
      { name: "N'Golo Kanté", wiki: "N'Golo_Kanté" },
      { name: "Manu Koné", wiki: "Manu_Koné" },
      { name: "Adrien Rabiot" },
      { name: "Aurélien Tchouaméni", wiki: "Aurélien_Tchouaméni" },
      { name: "Warren Zaïre-Emery", wiki: "Warren_Zaïre-Emery" },
      { name: "Maghnes Akliouche" },
      { name: "Bradley Barcola" },
      { name: "Rayan Cherki" },
      { name: "Ousmane Dembélé", wiki: "Ousmane_Dembélé" },
      { name: "Désiré Doué", wiki: "Désiré_Doué" },
      { name: "Jean-Philippe Mateta" },
      { name: "Kylian Mbappé", wiki: "Kylian_Mbappé" },
      { name: "Michael Olise" },
      { name: "Marcus Thuram", wiki: "Marcus_Thuram" },
    ],
  },

  JPN: {
    manager: { name: "Hajime Moriyasu" },
    captain: { name: "Wataru Endo" },
    topScorer: { name: "Takefusa Kubo" },
    fullSquad: [
      { name: "Tomoki Hayakawa" },
      { name: "Keisuke Osako" },
      { name: "Aya Suzuka" },
      { name: "Yuto Nagatomo" },
      { name: "Shogo Taniguchi" },
      { name: "Ko Itakura" },
      { name: "Tsuyoshi Watanabe" },
      { name: "Takehiro Tomiyasu" },
      { name: "Hiroki Ito" },
      { name: "Ayumu Seko" },
      { name: "Yukinari Sugawara" },
      { name: "Junosuke Suzuki" },
      { name: "Wataru Endo" },
      { name: "Junya Ito" },
      { name: "Daichi Kamada" },
      { name: "Koki Ogawa" },
      { name: "Daizen Maeda" },
      { name: "Ritsu Doan" },
      { name: "Ao Tanaka" },
      { name: "Kaishu Sano" },
      { name: "Takefusa Kubo" },
      { name: "Ayase Ueda" },
      { name: "Keito Nakamura" },
      { name: "Ito Suzuki" },
      { name: "Kento Shiode" },
      { name: "Keisuke Goto" },
    ],
  },

  KOR: {
    manager: { name: "Hong Myung-bo" },
    captain: { name: "Son Heung-min" },
    topScorer: { name: "Son Heung-min" },
    fullSquad: [
      { name: "Jo Hyeon-woo" },
      { name: "Kim Seung-gyu" },
      { name: "Song Bum-keun" },
      { name: "Kim Moon-hwan" },
      { name: "Kim Min-jae", wiki: "Kim_Min-jae_(footballer,_born_1996)" },
      { name: "Kim Tae-hyon" },
      { name: "Park Jin-seob" },
      { name: "Seol Young-woo" },
      { name: "Jens Castrop" },
      { name: "Lee Ki-hyuk" },
      { name: "Lee Tae-seok" },
      { name: "Lee Han-beom" },
      { name: "Cho Yu-min" },
      { name: "Kim Jin-gyu" },
      { name: "Bae Jun-ho" },
      { name: "Paik Seung-ho" },
      { name: "Yang Hyun-jun" },
      { name: "Eom Ji-sung" },
      { name: "Lee Kang-in" },
      { name: "Lee Dong-gyeong" },
      { name: "Lee Jae-sung" },
      { name: "Hwang In-beom" },
      { name: "Hwang Hee-chan" },
      { name: "Son Heung-min" },
      { name: "Oh Hyeon-gyu" },
      { name: "Cho Gue-sung" },
    ],
  },

  NZL: {
    manager: { name: "Darren Bazeley" },
    captain: { name: "Chris Wood" },
    topScorer: { name: "Chris Wood" },
    fullSquad: [
      { name: "Max Crocombe" },
      { name: "Alex Paulsen" },
      { name: "Michael Woud" },
      { name: "Tim Payne" },
      { name: "Francis De Vries" },
      { name: "Tyler Bindon" },
      { name: "Michael Boxall" },
      { name: "Liberato Cacace" },
      { name: "Nando Pijnaker" },
      { name: "Finn Surman" },
      { name: "Callan Elliot" },
      { name: "Tommy Smith" },
      { name: "Joe Bell" },
      { name: "Matt Garbett" },
      { name: "Marko Stamenic" },
      { name: "Sarpreet Singh" },
      { name: "Alex Rufer" },
      { name: "Ryan Thomas" },
      { name: "Chris Wood" },
      { name: "Eli Just" },
      { name: "Kosta Barbarouses" },
      { name: "Ben Waine" },
      { name: "Ben Old" },
      { name: "Callum McCowatt" },
      { name: "Jesse Randall" },
      { name: "Lachlan Bayliss" },
    ],
  },

  SWE: {
    manager: { name: "Graham Potter" },
    captain: { name: "Victor Lindelöf", wiki: "Victor_Lindelöf" },
    topScorer: { name: "Viktor Gyökeres", wiki: "Viktor_Gyökeres" },
    fullSquad: [
      { name: "Viktor Johansson" },
      { name: "Kristoffer Nordfeldt" },
      { name: "Jacob Widell Zetterstrom" },
      { name: "Hjalmar Ekdal" },
      { name: "Gabriel Gudmundsson" },
      { name: "Isak Hien" },
      { name: "Emil Holm" },
      { name: "Gustaf Lagerbielke" },
      { name: "Victor Lindelöf", wiki: "Victor_Lindelöf" },
      { name: "Erik Smith" },
      { name: "Carl Starfelt" },
      { name: "Elliot Stroud" },
      { name: "Daniel Svensson" },
      { name: "Taha Ali" },
      { name: "Yasin Ayari" },
      { name: "Lucas Bergvall" },
      { name: "Jesper Karlstrom" },
      { name: "Ken Sema" },
      { name: "Mattias Svanberg" },
      { name: "Besfort Zeneli" },
      { name: "Alexander Bernhardsson" },
      { name: "Anthony Elanga" },
      { name: "Viktor Gyökeres", wiki: "Viktor_Gyökeres" },
      { name: "Alexander Isak" },
      { name: "Gustaf Nilsson" },
      { name: "Benjamin Nygren" },
    ],
  },

  TUN: {
    manager: { name: "Sabri Lamouchi" },
    captain: { name: "Ellyes Skhiri" },
    fullSquad: [
      { name: "Sabri Ben Hessen" },
      { name: "Abdelmouhib Chamakh" },
      { name: "Aymen Dahman" },
      { name: "Ali Abdi" },
      { name: "Adem Arous" },
      { name: "Mohamed Amine Ben Hamida" },
      { name: "Dylan Bronn" },
      { name: "Raed Chikhaoui" },
      { name: "Moutaz Neffati" },
      { name: "Omar Rekik" },
      { name: "Montassar Talbi" },
      { name: "Yan Valery" },
      { name: "Mortadha Ben Ouanes" },
      { name: "Anis Ben Slimane" },
      { name: "Ismael Gharbi" },
      { name: "Rani Khedira" },
      { name: "Mohamed Hadj Mahmoud" },
      { name: "Hannibal Mejbri" },
      { name: "Ellyes Skhiri" },
      { name: "Elias Achouri" },
      { name: "Khalil Ayari" },
      { name: "Firas Chaouat" },
      { name: "Rayan Elloumi" },
      { name: "Hazem Mastouri" },
      { name: "Elias Saad" },
      { name: "Sebastian Tounekti" },
    ],
  },

  // ── Squads not yet announced ───────────────────────────────────────────────

  ARG: {
    manager: { name: "Lionel Scaloni" },
    captain: { name: "Lionel Messi" },
    topScorer: { name: "Lionel Messi" },
    squadAnnouncementDue: "late May 2026",
    notable: [
      { name: "Emiliano Martínez", wiki: "Emiliano_Martínez_(footballer,_born_1992)" },
      { name: "Nicolás Otamendi", wiki: "Nicolás_Otamendi" },
      { name: "Rodrigo De Paul" },
      { name: "Alexis Mac Allister" },
      { name: "Enzo Fernández", wiki: "Enzo_Fernández" },
      { name: "Julián Álvarez", wiki: "Julián_Álvarez" },
      { name: "Lautaro Martínez", wiki: "Lautaro_Martínez" },
    ],
  },

  AUS: {
    manager: { name: "Tony Popovic" },
    captain: { name: "Mathew Ryan" },
    squadAnnouncementDue: "1 June 2026",
    notable: [{ name: "Aaron Mooy" }, { name: "Mitchell Duke" }],
  },

  CAN: {
    manager: { name: "Jesse Marsch" },
    captain: { name: "Alphonso Davies" },
    topScorer: { name: "Jonathan David" },
    squadAnnouncementDue: "29 May 2026",
    notable: [
      { name: "Cyle Larin" },
      { name: "Stephen Eustáquio", wiki: "Stephen_Eustáquio" },
      { name: "Tajon Buchanan" },
    ],
  },

  ENG: {
    manager: { name: "Thomas Tuchel" },
    captain: { name: "Harry Kane" },
    topScorer: { name: "Harry Kane" },
    squadAnnouncementDue: "22 May 2026",
    notable: [
      { name: "Jude Bellingham" },
      { name: "Phil Foden" },
      { name: "Bukayo Saka" },
      { name: "Declan Rice" },
      { name: "Cole Palmer" },
      { name: "Jordan Pickford" },
      { name: "John Stones" },
      { name: "Kobbie Mainoo" },
    ],
  },

  ESP: {
    manager: { name: "Luis de la Fuente" },
    captain: { name: "Álvaro Morata", wiki: "Álvaro_Morata" },
    topScorer: { name: "Álvaro Morata", wiki: "Álvaro_Morata" },
    squadAnnouncementDue: "25 May 2026",
    notable: [
      { name: "Lamine Yamal" },
      { name: "Rodri", wiki: "Rodri_(footballer,_born_2002)" },
      { name: "Pedri" },
      { name: "Gavi" },
      { name: "Nico Williams" },
      { name: "Dani Carvajal" },
      { name: "Unai Simón", wiki: "Unai_Simón" },
    ],
  },

  GER: {
    manager: { name: "Julian Nagelsmann" },
    captain: { name: "Joshua Kimmich" },
    topScorer: { name: "Kai Havertz" },
    squadAnnouncementDue: "21 May 2026",
    notable: [
      { name: "Florian Wirtz" },
      { name: "Jamal Musiala" },
      { name: "Antonio Rüdiger", wiki: "Antonio_Rüdiger" },
      { name: "Manuel Neuer" },
      { name: "İlkay Gündoğan", wiki: "İlkay_Gündoğan" },
      { name: "Leroy Sané", wiki: "Leroy_Sané" },
    ],
  },

  MAR: {
    manager: { name: "Mohamed Ouahbi" },
    captain: { name: "Achraf Hakimi" },
    topScorer: { name: "Youssef En-Nesyri" },
    squadAnnouncementDue: "21 May 2026",
    notable: [
      { name: "Hakim Ziyech" },
      { name: "Sofyan Amrabat" },
      { name: "Yassine Bounou" },
    ],
  },

  MEX: {
    manager: { name: "Javier Aguirre" },
    captain: { name: "Edson Álvarez", wiki: "Edson_Álvarez" },
    topScorer: { name: "Raúl Jiménez", wiki: "Raúl_Jiménez" },
    squadAnnouncementDue: "late May 2026",
    notable: [
      { name: "Hirving Lozano" },
      { name: "Guillermo Ochoa" },
      { name: "Santiago Giménez", wiki: "Santiago_Giménez" },
    ],
  },

  NED: {
    manager: { name: "Ronald Koeman" },
    captain: { name: "Virgil van Dijk" },
    topScorer: { name: "Memphis Depay" },
    squadAnnouncementDue: "25 May 2026",
    notable: [
      { name: "Frenkie de Jong" },
      { name: "Cody Gakpo" },
      { name: "Xavi Simons" },
      { name: "Denzel Dumfries" },
      { name: "Nathan Aké", wiki: "Nathan_Aké" },
    ],
  },

  POR: {
    manager: { name: "Roberto Martínez", wiki: "Roberto_Martínez_(footballer)" },
    captain: { name: "Cristiano Ronaldo" },
    topScorer: { name: "Cristiano Ronaldo" },
    squadAnnouncementDue: "19 May 2026",
    notable: [
      { name: "Bernardo Silva" },
      { name: "Bruno Fernandes" },
      { name: "Rafael Leão", wiki: "Rafael_Leão" },
      { name: "Diogo Jota" },
      { name: "Rúben Dias", wiki: "Rúben_Dias" },
      { name: "João Cancelo", wiki: "João_Cancelo" },
    ],
  },

  SEN: {
    manager: { name: "Pape Thiaw" },
    captain: { name: "Kalidou Koulibaly" },
    topScorer: { name: "Sadio Mané", wiki: "Sadio_Mané" },
    squadAnnouncementDue: "late May 2026",
    notable: [
      { name: "Édouard Mendy", wiki: "Édouard_Mendy" },
      { name: "Ismaïla Sarr", wiki: "Ismaïla_Sarr" },
    ],
  },

  USA: {
    manager: { name: "Mauricio Pochettino" },
    captain: { name: "Christian Pulisic" },
    topScorer: { name: "Christian Pulisic" },
    squadAnnouncementDue: "26 May 2026",
    notable: [
      { name: "Weston McKennie" },
      { name: "Tyler Adams" },
      { name: "Folarin Balogun" },
      { name: "Gio Reyna" },
      { name: "Matt Turner", wiki: "Matt_Turner_(soccer)" },
    ],
  },
};
